#!/bin/sh
# By Jon Dehdari, 2016
# See README.md for details

hosts=$*
cmd="nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits"

visualize() {
	card_info=$*
	for card in $card_info; do
		printf " %3s%%: [" $card
		for tick in $(seq 0 1 $card); do
			printf "|"
		done
		# Complementing spaces
		for tick in $(seq $card 1 100); do
			printf " "
		done
		printf "]\n"
	done
	printf "\n"
}

# If command-line argument is a regular file, process each line in it
if [ -f $hosts ]; then
	while read host; do
		case $host in ''|\#*) continue;; esac  # skip commented out lines
		echo "$host:"
		card_info=$(ssh -n $host $cmd)
		visualize "$card_info"
	done < $hosts
else
	# Otherwise assume command-line arguments are a list of hosts
	for host in $hosts; do
		echo "$host"
		card_info=$(ssh $host $cmd)
		visualize "$card_info"
	done
fi
