#!/bin/sh
# By Jon Dehdari, 2016
# See README.md for details

hosts=$*
cmd="nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader"

# If command-line argument is a regular file, process each line in it
if [ -f $hosts ]; then
	while read host; do
		case $host in ''|\#*) continue;; esac  # skip commented out lines
		echo "$host"
		ssh -n $host $cmd
	done < $hosts
else
	# Otherwise assume command-line arguments are a list of hosts
	for host in $hosts; do
		echo "$host"
		ssh $host $cmd
	done
fi
